name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: |
        sudo apt-get update && sudo apt-get install libsysfs-dev
        cmake . -Bbuild
    - name: make
      run: |
        cd build
        make
    - name: make test
      run: |
        cd build
        make test
